name: Tests
on: [push]
jobs:
  easytest:
    uses: ./.github/workflows/testTemplate.yml
    with:
      project: easytest
  dep-copy:
    uses: ./.github/workflows/testTemplate.yml
    with:
      project: dep-copy